services:
  backend-server:
    build: backend-server/.
    volumes:
      - ./backend-server:/app
    ports:
      - 8000:8000

  disnake-bot:
    build: disnake-bot/.
    volumes:
      - ./disnake-bot:/app

volumes:
  backend-server: