services:
  backend-server:
    build: backend-server/.
    volumes:
      - ./backend-server:/app

  disnake-bot:
    build: disnake-bot/.
    volumes:
      - ./disnake-bot:/app

volumes:
  backend-server: