version: '3.8'
services:
  backend-server:
    build: backend-server/.

  disnake-bot:
    build: disnake-bot/.
    volumes:
      - ./disnake-bot:/app
    environment:
      - SERVER_ENDPOINT=http://backend-server:8000/