whitelist:
  not_registred: "Сперва зарегистрируйтесь на сервере!"

chat:
  sent_code: "§6Вам в ЛС отправлен код! Введите его в чат §7[T] §6чтобы авторизироваться."
  success_auth: "§aВы успешно авторизировались!"

  cant_break_blocks: "§cВы не можете разрушать блоки до авторизации!"
  cant_place_blocks: "§cВы не можете устанавливать блоки до авторизации!"
  cant_inventory: "§cВы не можете открывать инвентарь до авторизации!"
  cant_throw: "§cВы не можете выбрасывать предметы до авторизации!"
  cant_attak: "§cВы не можете атаковать до авторизации!"
  cant_use: "§cВы не можете взаимодействовать с объектами до авторизации!"
  cant_command: "§cВы не можете отправлять команды до авторизации!"
  cant_chat: "§cВы не можете писать в чат до авторизации!"

backend:
  endpoint: "http://localhost:8000/"
  disable: "Сервер на тех. работах!"
  error: "Не удалось выполнить проверку регестраци!"